"""AES-256-GCM vault and key derivation. Master key never leaves the process."""

from __future__ import annotations

import base64
import hashlib
import hmac
import os
import secrets
from pathlib import Path
from threading import Lock

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives import hashes

from app.utils.env import env, load_env
from app.utils.file_manager import ROOT
from app.utils.logger import get_logger

log = get_logger("crypto")

MAGIC = b"FGDB1\x00"
INFO_DB = b"framegenius-db-v1"
INFO_COL = b"framegenius-col-v1"
INFO_TOK = b"framegenius-tok-v1"


def _b64(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).decode("ascii")


def _b64d(text: str) -> bytes:
    pad = "=" * (-len(text) % 4)
    return base64.urlsafe_b64decode(text + pad)


def generate_master_key() -> str:
    return _b64(os.urandom(32))


def _normalize_master(raw: str) -> bytes:
    text = (raw or "").strip()
    if not text:
        raise RuntimeError("FRAMEGENIUS_MASTER_KEY is empty")
    try:
        decoded = _b64d(text)
        if len(decoded) >= 32:
            return decoded[:32]
    except Exception:
        pass
    return hashlib.sha256(text.encode("utf-8")).digest()


def derive_key(master: bytes, salt: bytes, info: bytes) -> bytes:
    return HKDF(algorithm=hashes.SHA256(), length=32, salt=salt, info=info).derive(master)


class CryptoVault:
    """Process-wide encrypt/decrypt using the studio master key."""

    def __init__(self, master_key: str) -> None:
        self._master = _normalize_master(master_key)

    def encrypt_bytes(self, plaintext: bytes, *, info: bytes = INFO_COL) -> bytes:
        salt = os.urandom(16)
        nonce = os.urandom(12)
        key = derive_key(self._master, salt, info)
        token = AESGCM(key).encrypt(nonce, plaintext, info)
        return MAGIC + salt + nonce + token

    def decrypt_bytes(self, blob: bytes, *, info: bytes = INFO_COL) -> bytes:
        if not blob.startswith(MAGIC):
            raise ValueError("Not a FrameGenius ciphertext")
        body = blob[len(MAGIC) :]
        salt, nonce, token = body[:16], body[16:28], body[28:]
        key = derive_key(self._master, salt, info)
        return AESGCM(key).decrypt(nonce, token, info)

    def encrypt_text(self, text: str) -> str:
        return _b64(self.encrypt_bytes(text.encode("utf-8"), info=INFO_COL))

    def decrypt_text(self, token: str) -> str:
        return self.decrypt_bytes(_b64d(token), info=INFO_COL).decode("utf-8")

    def encrypt_db(self, raw: bytes) -> bytes:
        return self.encrypt_bytes(raw, info=INFO_DB)

    def decrypt_db(self, blob: bytes) -> bytes:
        return self.decrypt_bytes(blob, info=INFO_DB)

    def hmac(self, value: str) -> str:
        digest = hmac.new(self._master, value.encode("utf-8"), hashlib.sha256).hexdigest()
        return digest

    def fingerprint(self) -> str:
        return hashlib.sha256(self._master + INFO_TOK).hexdigest()[:16]


_LOCK = Lock()
_VAULT: CryptoVault | None = None


def upsert_env(path: Path, key: str, value: str) -> None:
    """Set key=value in a .env file, replacing an empty or existing line."""
    path.parent.mkdir(parents=True, exist_ok=True)
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    lines: list[str] = []
    found = False
    prefix = f"{key}="
    for line in current.splitlines():
        stripped = line.strip()
        if stripped.startswith(prefix) or stripped.startswith(f"{key} ="):
            lines.append(f"{key}={value}")
            found = True
        else:
            lines.append(line)
    if not found:
        if lines and lines[-1] != "":
            lines.append("")
        lines.append("# --- generated by FrameGenius bootstrap — do not commit ---")
        lines.append(f"{key}={value}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    _chmod_private(path)
    os.environ[key] = value


def ensure_master_key(root: Path | None = None) -> str:
    """Load or create FRAMEGENIUS_MASTER_KEY and persist it to .env."""
    load_env(root)
    existing = env("FRAMEGENIUS_MASTER_KEY")
    base = root or ROOT
    env_path = base / ".env"
    if existing:
        # Keep .env in sync if the line is blank or missing.
        text = env_path.read_text(encoding="utf-8") if env_path.exists() else ""
        if f"FRAMEGENIUS_MASTER_KEY={existing}" not in text:
            upsert_env(env_path, "FRAMEGENIUS_MASTER_KEY", existing)
        return existing
    key = generate_master_key()
    upsert_env(env_path, "FRAMEGENIUS_MASTER_KEY", key)
    return key


def get_vault() -> CryptoVault:
    global _VAULT
    with _LOCK:
        if _VAULT is None:
            _VAULT = CryptoVault(ensure_master_key())
        return _VAULT


def reset_vault() -> None:
    global _VAULT
    with _LOCK:
        _VAULT = None


def _chmod_private(path: Path) -> None:
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass


def random_token(nbytes: int = 32) -> str:
    return secrets.token_urlsafe(nbytes)


def hash_secret(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def hash_password(password: str) -> str:
    try:
        import bcrypt

        return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt(rounds=12)).decode("ascii")
    except Exception:
        salt = os.urandom(16)
        dk = hashlib.scrypt(password.encode("utf-8"), salt=salt, n=2**14, r=8, p=1, dklen=32)
        return f"scrypt${salt.hex()}${dk.hex()}"


def verify_password(password: str, stored: str) -> bool:
    if stored.startswith("scrypt$"):
        _, salt_hex, dk_hex = stored.split("$", 2)
        dk = hashlib.scrypt(
            password.encode("utf-8"),
            salt=bytes.fromhex(salt_hex),
            n=2**14,
            r=8,
            p=1,
            dklen=32,
        )
        return hmac.compare_digest(dk.hex(), dk_hex)
    try:
        import bcrypt

        return bcrypt.checkpw(password.encode("utf-8"), stored.encode("ascii"))
    except Exception:
        return False


def strong_password(length: int = 18) -> str:
    alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%+="
    return "".join(secrets.choice(alphabet) for _ in range(length))
